import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/providers/auth-provider";
import RootProvider from "@/components/providers/root-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quickSand = Quicksand({
	variable: "--font-quicksand",
	subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
			<AuthProvider>
				<html lang="en">
					<body className={`${quickSand.className}  antialiased`}>
						<RootProvider>{children}</RootProvider>
					</body>
				</html>
			</AuthProvider>
		);
}
